Добавила ошибки: нельзя подписаться на себя или повторно расшарить карту
Online-discount-card-service/osdc_backend pull request #102
Opened 2023-12-09 07:35 UTC by Aenika

Добавила проверки:
- с самим собой нельзя пошерить;
- нельзя пошерить с тем, у кого уже есть эта карта.

2023-12-09 10:27 UTC, sldmxm requested changes

2023-12-09 10:27 UTC, sldmxm commented on backend/api/views.py
> +            if request.user.email == email:
Лучше перенести выше (после 361), чтобы лишний раз не дергать БД

2023-12-09 19:38 UTC, Aenika commented
Upd: исправила последовательность действий при share, добавила те тесты, которые проверяют действия share внутри сервиса

2023-12-10 12:39 UTC, sldmxm requested changes
Отлично
Предлагаю поправить тесты

2023-12-10 12:39 UTC, sldmxm commented on backend/api/tests/test_api.py
> +            kwargs={'pk': f'{self.card_user_not_fav.id}'}
делиться лучше картой, владельцем которой он является, если потом команда решит, что нельзя делиться не своими картами, эту часть переписывать не прийдется, правда, надо будет дописать тест на это тоже )

2023-12-10 12:39 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        self.assertFalse(UserCards.objects.get(
тоже стоит написать сообщение в случае не выполнения проверки

2023-12-10 12:39 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        response1 = self.auth_client.post(url, {'email': email}, format='json')
я бы разбил тесты - один удачное выполнение, второй (и третий) отработка крайних случаев, `response1` нам как бы уже подсказывает, что уже пора )

2023-12-10 12:39 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        shared_cards = UserCards.objects.filter(
думаю, это избыточная проверка, учитывая, что у нас в модели требуется уникальность пользователь-карта

2023-12-10 12:39 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        response2 = self.auth_client.post(
ну да, это бы я выделил в третий тест

2023-12-10 12:39 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        card_shared_with_self = UserCards.objects.filter(
тоже избыточно

2023-12-10 12:39 UTC, sldmxm commented on backend/core/consts.py
> +            f'Вы не можете поделиться картой с самим собой.'
Первая строчка кажется лишней, а без нее можно не заводить отдельный метод

2023-12-10 16:42 UTC, Aenika commented on backend/api/tests/test_api.py
> +            kwargs={'pk': f'{self.card_user_not_fav.id}'}
по моим расчётам, карта, которая не в избранном, должна входить в число тех, которыми он владеет)
но можно сделать что-то более очевидное.

2023-12-10 17:48 UTC, sldmxm commented on backend/api/tests/test_api.py
> +            kwargs={'pk': f'{self.card_user_not_fav.id}'}
> по моим расчётам, карта, которая не в избранном, должна входить в число тех, которыми он владеет) но можно сделать что-то более очевидное.

это зависит от констант сверху, а они могут поменяться

2023-12-10 17:58 UTC, sldmxm approved these changes

2023-12-10 17:58 UTC, sldmxm commented on backend/api/tests/fixtures.py
> +        cls.card_user_own = card_user_own.card
можно без промежуточной переменной, но не принципиально

2023-12-10 17:58 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        url = reverse(
можно сделать реверс на весь новый урл

2023-12-10 19:36 UTC, merged