Добавлены тесты кастом.djoser
Online-discount-card-service/osdc_backend pull request #104
Opened 2023-12-13 17:19 UTC by Aenika

Добавила три теста.
Есть нюанс: при тестировании ручки users/password-reset/ ответ корректный, но письмо не отправляется (хотя при ручном тестировании отправляется). Возможно, это потому, что в части отправления письма мы ничего не отправляли и он аботает у Djoser "из коробки" - собственно, возможно, по той же причине это необязательно и тестировать. Сама ручка, как кастомизированная ручка, работает корректно, и на тест отвечает корректно тоже.

2023-12-13 18:44 UTC, sldmxm requested changes
Надо еще написать тесты:
- что отправленный токен из письма активирует почту пользователя
- (опционально) что при сбросе пароля токен из письма живой и с его помощью можно поменять пароль

2023-12-13 18:44 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        """ользователь может запросить восстановление пароля."""
Опечатка в первом слове

2023-12-13 18:44 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        response = self.client.post(
url лучше получать через reverse

2023-12-17 15:05 UTC, Aenika commented
Сделала тесты (два варианта) активации почты пользователя, но! Они работают, только если явно прописать во вью ручку activation. Надо ли оно нам? (ручка работает, в общем-то)

2023-12-17 20:42 UTC, sldmxm requested changes

2023-12-17 20:42 UTC, sldmxm commented on backend/api/tests/test_api.py
> +            reverse('api:user-list') + 'reset_password/',
Там, скорее всего, есть свой реверс прямой

2023-12-17 20:42 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        self.assertIn('testemail@test.ru', mail.outbox[0].recipients())
Можно email, раз уж есть переменная )

2023-12-17 20:42 UTC, sldmxm commented on backend/api/views.py
> +    @action(["post"], detail=False)
Странно, без переопределения не работает тест?
Думаю, из-за теста точно не стоит переопределять метод

2023-12-17 21:12 UTC, sldmxm commented on backend/api/tests/test_api.py
> +        self.assertTrue(user.is_active, 'Не удалось активировать почту.')
А! Понял в чем проблема.
Мы сам объект user не меняем, djoser меняет запись в БД, а нам надо проверить, что данные изменились, для этого надо вставить строчку перед 509 
`user.refresh_from_db()`
так все будет работать ок и без переопределения метода activation

2023-12-18 14:48 UTC, sldmxm approved these changes
Отлично!

2023-12-18 15:53 UTC, merged