Fix/shop
Online-discount-card-service/osdc_backend pull request #19
Opened 2023-11-15 13:42 UTC by Aenika

В модели магазина добавила, что поля необязательные - все, кроме name. В поле изображения нужно будет добавить путь до дефолтной картинки ещё.

2023-11-15 19:21 UTC, sldmxm requested changes

2023-11-15 19:21 UTC, sldmxm commented on backend/api/serializers.py
> +    image = Base64ImageField(read_only=True)
Не понимаю зачем в base64, где то в документации? 
можно же просто путь отдавать к картинке,  что-то вроде:
````
    image = serializers.SerializerMethodField('get_image_url', read_only=True)
...
    def get_image_url(self, obj):
        """Возвращает относительный путь изображения."""
        if obj.image:
            return obj.image.url
        return None

2023-11-15 19:21 UTC, sldmxm commented on backend/api/views.py
> +    permission_classes = (AllowAny,)
Не уверен, что на просмотр должен быть доступ без авторизации. Хотя, на начальном экране, кажется, есть список магазинов, может и нужен. 

Но точно надо сделать отбор магазинов по "верификации", пользователи должны видеть только выверенный список магазинов validation == True.

2023-11-15 19:58 UTC, Aenika commented on backend/api/views.py
> +    permission_classes = (AllowAny,)
На всякий случай, уточняющие вопросы. Может быть, ты их как раз с ребятами в воскресенье обсуждал, а я  пропустила.
У нас в основном этот список магазинов нужен для того, чтобы был выпадающий список магазинов при создании карточки, иначе будут каждый раз создавать новый. Если детский мир, к примеру, не верифицированный, то у нас в базе будет Детских Миров по числу детных пользователей.
Второй момент: добавляет юзер карточку с новым магазином, а через год у магазина новая программа лояльности, и нужно делать новую скидочную карточку. В таком случае будет ещё одна запись того же магазина от того же пользователя при добавлении новой карточки.

Если на сегодняшнем этапе это ОК, то добавлю фильтр.

2023-11-15 21:59 UTC, sldmxm commented on backend/api/views.py
> +    permission_classes = (AllowAny,)
Да, договорилсь именно так - если пользователь хочет создать магазин не из списка, создает, но другие его не видят до тех пор, пока админ (или умный алгоритм) не поставит галку "верифицирован" и не соберет все одинаковые в одну сущность

2023-11-15 22:15 UTC, sldmxm commented on backend/api/views.py
> +    permission_classes = (AllowAny,)
> Не уверен, что на просмотр должен быть доступ без авторизации. Хотя, на начальном экране, кажется, есть список магазинов, может и нужен.

Можно отдавать анонимно, я спросил

2023-11-16 11:42 UTC, Aenika commented on backend/api/serializers.py
> +    image = Base64ImageField(read_only=True)
Посидела над картинками, потом посмотрела, что вы н асервере состыковали back+front. Получается, с изначальным вариантом поле ImageField работает, там оно автоматически генерирует абсолютный урл. Может, так и оставить, если это был рабочий вариант?
Сделала соответствующий новый коммит: https://github.com/Online-discount-card-service/osdc_backend/pull/19/commits/5d97e070367255f94c4c873543356dc2205387c7

2023-11-16 13:04 UTC, sldmxm commented on backend/api/serializers.py
> +    image = Base64ImageField(read_only=True)
Можно пока сделать полный урл, да, посмотрим, как будет работать. 
я не помню, почему делал относительный, но помню, было больно )

2023-11-16 13:57 UTC, sldmxm approved these changes

2023-11-16 15:17 UTC, merged