рмFix/views and serializers
Online-discount-card-service/osdc_backend pull request #21
Opened 2023-11-15 19:40 UTC by skiba-py

Исправил сериализаторы Card в соответствии с новыми моделями.

2023-11-15 21:57 UTC, sldmxm requested changes
Возможно, мне надо глубже погрузиться в логику, но пока некоторые вещи непонятны (

2023-11-15 21:57 UTC, sldmxm commented on backend/api/serializers.py
> +from django.core.files.base import ContentFile
тремя строками выше уже есть

2023-11-15 21:57 UTC, sldmxm commented on backend/api/serializers.py
> +    image_card = Base64ImageField(
лучше отдавать адрес картинки
```
image = serializers.SerializerMethodField('get_image_url', read_only=True)


    def get_image_url(self, obj):
        """Возвращает относительный путь изображения."""
        if obj.image:
            return obj.image.url
        return None
```

2023-11-15 21:57 UTC, sldmxm commented on backend/api/serializers.py
>      def update(self, instance, validated_data):
Не понимаю, зачем это (

2023-11-15 21:57 UTC, sldmxm commented on backend/api/serializers.py
>  class CardForUserSerializer(serializers.ModelSerializer):
И это не понимаю. Почему нельзя использовать CardSerializer?

2023-11-16 15:39 UTC, Aenika commented on backend/api/views.py
Во вью Карт нужно добавить фильтр, чтобы выдавались карты только текущего пользователя, метод get_queryset
Кажется, в нашем случае это что-то типа:
def get_queryset(self):
    return Card.objects.filter(card_favourites__user=self.request.user)

2023-11-16 15:41 UTC, sldmxm commented on backend/api/views.py
Лучше через uself.request.user.cards (если у нас есть такое поле, если нет, стоит сделать :)

2023-11-17 11:10 UTC, sldmxm reviewed
Спасибо!
Дальше допилю до требований

2023-11-17 22:19 UTC, closed without merging

2023-11-17 22:19 UTC, sldmxm commented
Дальше в другой ветке