Fix/users
Online-discount-card-service/osdc_backend pull request #40
Opened 2023-11-18 22:12 UTC by KrasinAD

Если все так, то с мержи в develop.

2023-11-18 22:33 UTC, sldmxm requested changes
С паролем нужно переделать

С вьюсетами и сериалазерами все ок?

2023-11-18 22:33 UTC, sldmxm commented on backend/users/consts.py
> +MAX_LENGTH_PASSWORD = 20
не полетит (
это не длинна пароля, это длинна поля - пароль хешируется, а хешу  надо то ли 128, то ли 255 символов в этом поле, поэтому создание любого пользователя с любым паролем приведет к ошибке
в общем, как мне кажется, стоит вообще удалить и константу, и max_length= в модели

2023-11-18 22:33 UTC, sldmxm commented on backend/users/migrations/0006_alter_user_password_alter_user_phone_number.py
> +            field=models.CharField(max_length=20, verbose_name='Пароль'),
здесь можно будет руками убрать max_length=20, оставить только verbose_name='Пароль'
чтобы не делать еще одну миграцию

ну и проверить, конечно

2023-11-18 22:36 UTC, sldmxm commented on backend/users/migrations/0006_alter_user_password_alter_user_phone_number.py
> +            field=models.CharField(max_length=20, verbose_name='Пароль'),
проверить - это, например, переименовать локальный файл sqlite, если там что-то полезное, провести миграции, создав новый, проверить, что все создалось и работает, создав суперюзера
ну и потом думать, что делать с данными из старой )

2023-11-19 12:14 UTC, KrasinAD commented on backend/users/migrations/0006_alter_user_password_alter_user_phone_number.py
> +            field=models.CharField(max_length=20, verbose_name='Пароль'),
Удалил файл 06 в миграциях и добавил в 05 к параметру телефона название, вроде работает как надо.

2023-11-19 14:45 UTC, sldmxm commented on backend/users/consts.py
> +MAX_LENGTH_PASSWORD = 20
> Вернул обратно на max_length=255, удалить не получилось ругается на отсутствие параметра max_length=255

надо удалить и в константах, и в модели max_length=

2023-11-19 14:49 UTC, sldmxm commented on backend/users/migrations/0006_alter_user_password_alter_user_phone_number.py
> +            field=models.CharField(max_length=20, verbose_name='Пароль'),
> Удалил файл 06 в миграциях и добавил в 05 к параметру телефона название, вроде работает как надо.

в любом случае, после удаления требований из модели по длинне поля пароля, надо будет делать миграцию
имеет смысл вернуть в 05 как было, и сделать 06

2023-11-19 16:15 UTC, sldmxm approved these changes

2023-11-19 16:17 UTC, merged